// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: sushka_prj

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_mainscreen;
lv_obj_t * ui_temeratureindicator;
void ui_event_temperature(lv_event_t * e);
lv_obj_t * ui_temperature;
lv_obj_t * ui_targettemp;
lv_obj_t * ui_timeft;
void ui_event_onoffarea(lv_event_t * e);
lv_obj_t * ui_onoffarea;
lv_obj_t * ui_mintemp;
lv_obj_t * ui_maxtemp;
lv_obj_t * ui_online;
void ui_event_minus60(lv_event_t * e);
lv_obj_t * ui_minus60;
lv_obj_t * ui_Label1;
void ui_event_minus30m(lv_event_t * e);
lv_obj_t * ui_minus30m;
lv_obj_t * ui_Label2;
void ui_event_plus1h(lv_event_t * e);
lv_obj_t * ui_plus1h;
lv_obj_t * ui_Label3;
void ui_event_plus30m(lv_event_t * e);
lv_obj_t * ui_plus30m;
lv_obj_t * ui_Label4;
lv_obj_t * ui_fanpanel;
lv_obj_t * ui_Label7;
lv_obj_t * ui_fanspeed;
void ui_event_setfanspeed(lv_event_t * e);
lv_obj_t * ui_setfanspeed;
lv_obj_t * ui_sensor;
lv_obj_t * ui_crrettemp;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label18;
lv_obj_t * ui_status;
lv_obj_t * ui_errormodal;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_errortext;
lv_obj_t * ui_Label6;


// SCREEN: ui_config
void ui_config_screen_init(void);
lv_obj_t * ui_config;
lv_obj_t * ui_Container3;
lv_obj_t * ui_maxmenutemp;
lv_obj_t * ui_Label5;
lv_obj_t * ui_maxcelsius;
lv_obj_t * ui_minmenutemp;
lv_obj_t * ui_Label8;
lv_obj_t * ui_mincelsius;
lv_obj_t * ui_Label9;
lv_obj_t * ui_fan;
lv_obj_t * ui_Label17;
lv_obj_t * ui_fanstart;
lv_obj_t * ui_minmenutemp2;
lv_obj_t * ui_Label19;
lv_obj_t * ui_tgtcelsius;
lv_obj_t * ui_pids;
void ui_event_pid_ki(lv_event_t * e);
lv_obj_t * ui_pid_ki;
void ui_event_pid_kp(lv_event_t * e);
lv_obj_t * ui_pid_kp;
void ui_event_pid_kd(lv_event_t * e);
lv_obj_t * ui_pid_kd;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_ku_Container1;
lv_obj_t * ui_Label20;
lv_obj_t * ui_ku_value;
lv_obj_t * ui_tu_Container2;
lv_obj_t * ui_Label21;
lv_obj_t * ui_tu_value;
void ui_event_pidselect(lv_event_t * e);
lv_obj_t * ui_pidselect;
void ui_event_reset_pid_button(lv_event_t * e);
lv_obj_t * ui_reset_pid_button;
lv_obj_t * ui_Label14;
void ui_event_return(lv_event_t * e);
lv_obj_t * ui_return;
lv_obj_t * ui_Label15;
void ui_event_reset_pid(lv_event_t * e);
lv_obj_t * ui_reset_pid;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Container5;
void ui_event_R25_Ohm(lv_event_t * e);
lv_obj_t * ui_R25_Ohm;
void ui_event_R_div_Ohm(lv_event_t * e);
lv_obj_t * ui_R_div_Ohm;
void ui_event_beta(lv_event_t * e);
lv_obj_t * ui_beta;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_version;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_temperature(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        settemp_cb(e);
    }
}
void ui_event_onoffarea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        onoff_cb(e);
    }
}
void ui_event_minus60(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        minus1h_cb(e);
    }
}
void ui_event_minus30m(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        minuns30m_cb(e);
    }
}
void ui_event_plus1h(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        plus1h_cb(e);
    }
}
void ui_event_plus30m(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        plus30m_cb(e);
    }
}
void ui_event_setfanspeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setfanspeed_cb(e);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_config, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_config_screen_init);
        load_menu_config(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        continue_cb(e);
    }
}
void ui_event_pid_ki(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_pid_ki);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_pid_kp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_pid_kp);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_pid_kd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_pid_kd);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_pidselect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        pidselected(e);
    }
}
void ui_event_reset_pid_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
        save_menu_data(e);
    }
}
void ui_event_reset_pid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        reset_menu_pid(e);
    }
}
void ui_event_R25_Ohm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_R25_Ohm);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_R_div_Ohm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_R_div_Ohm);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_beta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_beta);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_config_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
