// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sushka_prj

#ifndef _SUSHKA_PRJ_UI_H
#define _SUSHKA_PRJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_mainscreen;
extern lv_obj_t * ui_temeratureindicator;
void ui_event_temperature(lv_event_t * e);
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_targettemp;
extern lv_obj_t * ui_timeft;
void ui_event_onoffarea(lv_event_t * e);
extern lv_obj_t * ui_onoffarea;
extern lv_obj_t * ui_mintemp;
extern lv_obj_t * ui_maxtemp;
extern lv_obj_t * ui_online;
void ui_event_minus60(lv_event_t * e);
extern lv_obj_t * ui_minus60;
extern lv_obj_t * ui_Label1;
void ui_event_minus30m(lv_event_t * e);
extern lv_obj_t * ui_minus30m;
extern lv_obj_t * ui_Label2;
void ui_event_plus1h(lv_event_t * e);
extern lv_obj_t * ui_plus1h;
extern lv_obj_t * ui_Label3;
void ui_event_plus30m(lv_event_t * e);
extern lv_obj_t * ui_plus30m;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_fanpanel;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_fanspeed;
void ui_event_setfanspeed(lv_event_t * e);
extern lv_obj_t * ui_setfanspeed;
extern lv_obj_t * ui_sensor;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_crrettemp;
extern lv_obj_t * ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
