// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sushka

#ifndef _SUSHKA_UI_H
#define _SUSHKA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel1;
void ui_event_temperature(lv_event_t * e);
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_targettemp;
extern lv_obj_t * ui_crrettemp;
extern lv_obj_t * ui_timeft;
extern lv_obj_t * ui_humidity;
void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
void ui_event_minus60(lv_event_t * e);
extern lv_obj_t * ui_minus60;
extern lv_obj_t * ui_Label1;
void ui_event_minus30m(lv_event_t * e);
extern lv_obj_t * ui_minus30m;
extern lv_obj_t * ui_Label2;
void ui_event_plus1h(lv_event_t * e);
extern lv_obj_t * ui_plus1h;
extern lv_obj_t * ui_Label3;
void ui_event_plus30m(lv_event_t * e);
extern lv_obj_t * ui_plus30m;
extern lv_obj_t * ui_Label4;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_fanspeed;
extern lv_obj_t * ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
