// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sushka

#include "ui.h"

void settemp_cb(lv_event_t * e)
{
	// Your code here
}

void minus1h_cb(lv_event_t * e)
{
	// Your code here
}

void minuns30m_cb(lv_event_t * e)
{
	// Your code here
}

void plus1h_cb(lv_event_t * e)
{
	// Your code here
}

void plus30m_cb(lv_event_t * e)
{
	// Your code here
}

void onoff_cb(lv_event_t * e)
{
	// Your code here
}
