// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sushka

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void settemp_cb(lv_event_t * e);
void onoff_cb(lv_event_t * e);
void minus1h_cb(lv_event_t * e);
void minuns30m_cb(lv_event_t * e);
void plus1h_cb(lv_event_t * e);
void plus30m_cb(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
