// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: sushka_prj

#include "../ui.h"

void ui_config_screen_init(void)
{
    ui_config = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_config, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_config);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 63);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_maxmenutemp = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_maxmenutemp);
    lv_obj_set_width(ui_maxmenutemp, lv_pct(30));
    lv_obj_set_height(ui_maxmenutemp, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_maxmenutemp, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_maxmenutemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_maxmenutemp);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label5, "°C max");

    ui_maxcelsius = lv_dropdown_create(ui_maxmenutemp);
    lv_dropdown_set_options(ui_maxcelsius, "80\n90\n100\n110");
    lv_obj_set_width(ui_maxcelsius, 50);
    lv_obj_set_height(ui_maxcelsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_maxcelsius, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_maxcelsius, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_minmenutemp = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_minmenutemp);
    lv_obj_set_width(ui_minmenutemp, lv_pct(30));
    lv_obj_set_height(ui_minmenutemp, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_minmenutemp, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_minmenutemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_minmenutemp);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label8, "°C min");

    ui_mincelsius = lv_dropdown_create(ui_minmenutemp);
    lv_dropdown_set_options(ui_mincelsius, "50\n60\n70\n80\n");
    lv_obj_set_width(ui_mincelsius, 50);
    lv_obj_set_height(ui_mincelsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mincelsius, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_mincelsius, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label9 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label9, "temperature and fan");

    ui_fan = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_fan);
    lv_obj_set_width(ui_fan, lv_pct(30));
    lv_obj_set_height(ui_fan, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_fan, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_fan, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_fan);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label17, "% fan");

    ui_mincelsius2 = lv_dropdown_create(ui_fan);
    lv_dropdown_set_options(ui_mincelsius2, "25\n50\n75\n100");
    lv_obj_set_width(ui_mincelsius2, 50);
    lv_obj_set_height(ui_mincelsius2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mincelsius2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_mincelsius2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_minmenutemp2 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_minmenutemp2);
    lv_obj_set_width(ui_minmenutemp2, lv_pct(30));
    lv_obj_set_height(ui_minmenutemp2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_minmenutemp2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_minmenutemp2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_minmenutemp2);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label19, "°C tgt");

    ui_tgtcelsius = lv_dropdown_create(ui_minmenutemp2);
    lv_dropdown_set_options(ui_tgtcelsius, "60\n65\n70\n75\n80\n85\n90\n95\n100\n105\n");
    lv_obj_set_width(ui_tgtcelsius, 50);
    lv_obj_set_height(ui_tgtcelsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tgtcelsius, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_tgtcelsius, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_pids = lv_obj_create(ui_config);
    lv_obj_remove_style_all(ui_pids);
    lv_obj_set_height(ui_pids, 78);
    lv_obj_set_width(ui_pids, lv_pct(100));
    lv_obj_set_x(ui_pids, 0);
    lv_obj_set_y(ui_pids, 70);
    lv_obj_clear_flag(ui_pids, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_pids);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label10, "PID");

    ui_pid_ki = lv_textarea_create(ui_pids);
    lv_obj_set_width(ui_pid_ki, 103);
    lv_obj_set_height(ui_pid_ki, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_pid_ki, LV_ALIGN_BOTTOM_LEFT);
    if("0123456789." == "") lv_textarea_set_accepted_chars(ui_pid_ki, NULL);
    else lv_textarea_set_accepted_chars(ui_pid_ki, "0123456789.");
    lv_textarea_set_max_length(ui_pid_ki, 10);
    lv_textarea_set_text(ui_pid_ki, "45.79999954");
    lv_textarea_set_placeholder_text(ui_pid_ki, "Placeholder...");
    lv_textarea_set_one_line(ui_pid_ki, true);



    ui_pid_kp = lv_textarea_create(ui_pids);
    lv_obj_set_width(ui_pid_kp, 103);
    lv_obj_set_height(ui_pid_kp, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_pid_kp, LV_ALIGN_BOTTOM_MID);
    if("0123456789." == "") lv_textarea_set_accepted_chars(ui_pid_kp, NULL);
    else lv_textarea_set_accepted_chars(ui_pid_kp, "0123456789.");
    lv_textarea_set_max_length(ui_pid_kp, 10);
    lv_textarea_set_text(ui_pid_kp, "45.79999954");
    lv_textarea_set_placeholder_text(ui_pid_kp, "Placeholder...");
    lv_textarea_set_one_line(ui_pid_kp, true);



    ui_pid_kd = lv_textarea_create(ui_pids);
    lv_obj_set_width(ui_pid_kd, 103);
    lv_obj_set_height(ui_pid_kd, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_pid_kd, LV_ALIGN_BOTTOM_RIGHT);
    if("0123456789." == "") lv_textarea_set_accepted_chars(ui_pid_kd, NULL);
    else lv_textarea_set_accepted_chars(ui_pid_kd, "0123456789.");
    lv_textarea_set_max_length(ui_pid_kd, 10);
    lv_textarea_set_text(ui_pid_kd, "45.79999954");
    lv_textarea_set_placeholder_text(ui_pid_kd, "Placeholder...");
    lv_textarea_set_one_line(ui_pid_kd, true);



    ui_Label11 = lv_label_create(ui_pids);
    lv_obj_set_width(ui_Label11, 103);
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, 25);
    lv_label_set_text(ui_Label11, "Ki");
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_pids);
    lv_obj_set_width(ui_Label12, 103);
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 0);
    lv_obj_set_y(ui_Label12, 25);
    lv_obj_set_align(ui_Label12, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label12, "Kp");
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_pids);
    lv_obj_set_width(ui_Label13, 103);
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, 25);
    lv_obj_set_align(ui_Label13, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label13, "Kd");
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ku_Container1 = lv_obj_create(ui_pids);
    lv_obj_remove_style_all(ui_ku_Container1);
    lv_obj_set_width(ui_ku_Container1, lv_pct(25));
    lv_obj_set_height(ui_ku_Container1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ku_Container1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ku_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_ku_Container1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label20, "ku");

    ui_ku_value = lv_label_create(ui_ku_Container1);
    lv_obj_set_width(ui_ku_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ku_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ku_value, LV_ALIGN_TOP_RIGHT);

    ui_tu_Container2 = lv_obj_create(ui_pids);
    lv_obj_remove_style_all(ui_tu_Container2);
    lv_obj_set_width(ui_tu_Container2, lv_pct(25));
    lv_obj_set_height(ui_tu_Container2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_tu_Container2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_tu_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_tu_Container2);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label21, "tu");

    ui_tu_value1 = lv_label_create(ui_tu_Container2);
    lv_obj_set_width(ui_tu_value1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tu_value1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tu_value1, LV_ALIGN_TOP_RIGHT);

    ui_reset_pid_button = lv_btn_create(ui_config);
    lv_obj_set_width(ui_reset_pid_button, 100);
    lv_obj_set_height(ui_reset_pid_button, 34);
    lv_obj_set_align(ui_reset_pid_button, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_reset_pid_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_reset_pid_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_reset_pid_button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_button);
    ui_object_set_themeable_style_property(ui_reset_pid_button, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_button);

    ui_Label14 = lv_label_create(ui_reset_pid_button);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "exit");

    ui_return = lv_btn_create(ui_config);
    lv_obj_set_width(ui_return, 100);
    lv_obj_set_height(ui_return, 34);
    lv_obj_set_align(ui_return, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_return, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_return, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_return, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_button);
    ui_object_set_themeable_style_property(ui_return, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_button);

    ui_Label15 = lv_label_create(ui_return);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "save and exit");

    ui_reset_pid = lv_btn_create(ui_config);
    lv_obj_set_width(ui_reset_pid, 100);
    lv_obj_set_height(ui_reset_pid, 34);
    lv_obj_set_align(ui_reset_pid, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_reset_pid, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_reset_pid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_reset_pid, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_button);
    ui_object_set_themeable_style_property(ui_reset_pid, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_button);

    ui_Label16 = lv_label_create(ui_reset_pid);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "reset PID");

    ui_Container5 = lv_obj_create(ui_config);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 50);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, 150);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Container5);
    lv_dropdown_set_options(ui_Dropdown1, "PID basic\nPID less overshoot\nPID no overshoot");
    lv_obj_set_width(ui_Dropdown1, 178);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Keyboard1 = lv_keyboard_create(ui_config);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_height(ui_Keyboard1, 87);
    lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_Keyboard1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_button);
    ui_object_set_themeable_style_property(ui_Keyboard1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_button);

    lv_obj_add_event_cb(ui_pid_ki, ui_event_pid_ki, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pid_kp, ui_event_pid_kp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pid_kd, ui_event_pid_kd, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_reset_pid_button, ui_event_reset_pid_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_return, ui_event_return, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_reset_pid, ui_event_reset_pid, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_pid_ki);
    lv_obj_add_event_cb(ui_config, ui_event_config, LV_EVENT_ALL, NULL);

}
