// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sushka

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_height(ui_Panel3, lv_pct(100));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Panel3);
    lv_obj_set_width(ui_Panel1, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_Panel1, LV_SIZE_CONTENT);    /// 160
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperature = lv_arc_create(ui_Panel1);
    lv_obj_set_width(ui_temperature, 150);
    lv_obj_set_height(ui_temperature, 150);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_temperature, 65, 110);
    lv_arc_set_value(ui_temperature, 95);


    ui_targettemp = lv_label_create(ui_temperature);
    lv_obj_set_width(ui_targettemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_targettemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_targettemp, 0);
    lv_obj_set_y(ui_targettemp, -27);
    lv_obj_set_align(ui_targettemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_targettemp, "95");
    lv_obj_set_style_text_font(ui_targettemp, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_crrettemp = lv_label_create(ui_temperature);
    lv_obj_set_width(ui_crrettemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_crrettemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_crrettemp, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_crrettemp, "63");

    ui_timeft = lv_label_create(ui_temperature);
    lv_obj_set_width(ui_timeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeft, 1);
    lv_obj_set_y(ui_timeft, 14);
    lv_obj_set_align(ui_timeft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeft, "00:00");
    lv_obj_set_style_text_font(ui_timeft, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidity = lv_label_create(ui_temperature);
    lv_obj_set_width(ui_humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humidity, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_humidity, "33%");

    ui_Panel4 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel4, 100);
    lv_obj_set_height(ui_Panel4, 100);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minus60 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_minus60, 50);
    lv_obj_set_height(ui_minus60, 50);
    lv_obj_add_flag(ui_minus60, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minus60, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_minus60, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minus60, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_minus60, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minus60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_minus60);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "-1H");

    ui_minus30m = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_minus30m, 50);
    lv_obj_set_height(ui_minus30m, 125);
    lv_obj_set_x(ui_minus30m, 0);
    lv_obj_set_y(ui_minus30m, 55);
    lv_obj_add_flag(ui_minus30m, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_minus30m, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_minus30m, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minus30m, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_minus30m, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minus30m, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_minus30m);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "-30m");

    ui_plus1h = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_plus1h, 50);
    lv_obj_set_height(ui_plus1h, 50);
    lv_obj_set_align(ui_plus1h, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_plus1h, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_plus1h, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_plus1h, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_plus1h, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_plus1h, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plus1h, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_plus1h);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "+1H");

    ui_plus30m = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_plus30m, 50);
    lv_obj_set_height(ui_plus30m, 125);
    lv_obj_set_x(ui_plus30m, 0);
    lv_obj_set_y(ui_plus30m, 55);
    lv_obj_set_align(ui_plus30m, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_plus30m, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_plus30m, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_plus30m, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_plus30m, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_plus30m, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_plus30m, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_plus30m);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "+30m");

    ui_Slider2 = lv_slider_create(ui_Panel3);
    lv_slider_set_range(ui_Slider2, 25, 100);
    lv_slider_set_value(ui_Slider2, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, -1);
    lv_obj_set_y(ui_Slider2, 0);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_BOTTOM_MID);


    ui_Label7 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label7, "fan");

    ui_fanspeed = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_fanspeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fanspeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fanspeed, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_fanspeed, "80%");

    lv_obj_add_event_cb(ui_temperature, ui_event_temperature, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel4, ui_event_Panel4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minus60, ui_event_minus60, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_minus30m, ui_event_minus30m, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_plus1h, ui_event_plus1h, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_plus30m, ui_event_plus30m, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);

}
